#!/bin/bash

# Comprehensive Compliance Report Generator Script
# Creates a new timestamped directory structure for compliance audit reports
# Covers iGaming, IT/SaaS, and Data Protection frameworks

# Generate timestamp in YYYY-MM-DD-HHMM format
TIMESTAMP=$(date +"%Y-%m-%d-%H%M")
REPORT_DIR="docs/compliance_checks/$TIMESTAMP"

echo "Creating comprehensive compliance report directory: $REPORT_DIR"

# Create the main report directory
mkdir -p "$REPORT_DIR"

# Create comprehensive index with all frameworks
cat > "$REPORT_DIR/index.md" << EOF
# Comprehensive Compliance Audit Report - $TIMESTAMP

## Overview
This report contains the results of comprehensive compliance audits conducted on $(date +"%Y-%m-%d at %H:%M"), covering iGaming, IT/SaaS, and Data Protection frameworks.

## Core Compliance Frameworks

| Category | Framework | Status | Issues Found | Report Link |
|----------|-----------|--------|--------------|-------------|
| **iGaming Standards** | GLI (Gaming Laboratories International) | 🔄 In Progress | - | [GLI Report](./gli.md) |
| | MGA (Malta Gaming Authority) | 🔄 In Progress | - | [MGA Report](./mga.md) |
| | UKGC (UK Gambling Commission) | 🔄 In Progress | - | [UKGC Report](./ukgc.md) |
| | G4 (Global Gambling Guidance Group) | 🔄 In Progress | - | [G4 Report](./g4.md) |
| **IT/SaaS Standards** | SOC 2 | 🔄 In Progress | - | [SOC 2 Report](./soc2.md) |
| | ISO 27001 | 🔄 In Progress | - | [ISO 27001 Report](./iso27001.md) |
| | ISO 9001 | 🔄 In Progress | - | [ISO 9001 Report](./iso9001.md) |
| | PCI DSS | 🔄 In Progress | - | [PCI DSS Report](./pci_dss.md) |
| | CSA STAR | 🔄 In Progress | - | [CSA STAR Report](./csa_star.md) |
| | ITIL | 🔄 In Progress | - | [ITIL Report](./itil.md) |
| **Data Protection** | GDPR | 🔄 In Progress | - | [GDPR Report](./gdpr.md) |
| | UK DPA 2018 | 🔄 In Progress | - | [DPA 2018 Report](./dpa2018.md) |
| | CCPA/CPRA | 🔄 In Progress | - | [CCPA Report](./ccpa_cpra.md) |

## Testing & Certification Bodies

| Lab/Agency | Status | Issues Found | Report Link |
|------------|--------|--------------|-------------|
| eCOGRA | 🔄 In Progress | - | [eCOGRA Report](./ecogra.md) |
| iTech Labs | 🔄 In Progress | - | [iTech Labs Report](./itech_labs.md) |
| BMM Testlabs | 🔄 In Progress | - | [BMM Report](./bmm_testlabs.md) |
| Trisigma | 🔄 In Progress | - | [Trisigma Report](./trisigma.md) |
| Gaming Associates | 🔄 In Progress | - | [GA Report](./gaming_associates.md) |

## Regulatory Jurisdictions

| Jurisdiction | License Status | Compliance Status | Issues | Report Link |
|--------------|----------------|-------------------|--------|-------------|
| Gibraltar (GRA) | 🔄 In Progress | 🔄 In Progress | - | [Gibraltar Report](./gibraltar.md) |
| Alderney (AGCC) | 🔄 In Progress | 🔄 In Progress | - | [Alderney Report](./alderney.md) |
| Isle of Man (GSC) | 🔄 In Progress | 🔄 In Progress | - | [IoM Report](./isle_of_man.md) |
| Curaçao eGaming | 🔄 In Progress | 🔄 In Progress | - | [Curaçao Report](./curacao.md) |
| New Jersey (NJDGE) | 🔄 In Progress | 🔄 In Progress | - | [New Jersey Report](./new_jersey.md) |
| Pennsylvania (PGCB) | 🔄 In Progress | 🔄 In Progress | - | [Pennsylvania Report](./pennsylvania.md) |

## Summary Statistics

### By Category
- **iGaming Standards**: 4 frameworks
- **IT/SaaS Standards**: 6 frameworks
- **Data Protection**: 3 frameworks
- **Testing Labs**: 5 labs
- **Jurisdictions**: 6 jurisdictions

### Overall Compliance Health
- **Total Controls Audited**: -
- **Compliant**: -
- **Non-Compliant**: -
- **Observations**: -

## Navigation

- **Previous Report**: [Previous Report](../README.md#available-reports)
- **Next Report**: [Next Report](../README.md#available-reports)
- **All Reports**: [Compliance Reports Index](../README.md)

## Report Generation Info

- **Generated By**: Auditron AI Compliance Agent
- **Generation Time**: $(date +"%Y-%m-%d %H:%M:%S UTC")
- **Report Format Version**: 2.0
- **Frameworks Covered**: iGaming, IT/SaaS, Data Protection, Testing Labs, Regulatory Jurisdictions
EOF

# Define all frameworks and their categories
declare -A frameworks=(
    # Core iGaming Standards
    ["gli"]="GLI (Gaming Laboratories International)"
    ["mga"]="MGA (Malta Gaming Authority)"
    ["ukgc"]="UKGC (UK Gambling Commission)"
    ["g4"]="G4 (Global Gambling Guidance Group)"
    
    # IT/SaaS Standards
    ["soc2"]="SOC 2 Trust Services Criteria"
    ["iso27001"]="ISO 27001 Information Security Management System"
    ["iso9001"]="ISO 9001 Quality Management System"
    ["pci_dss"]="PCI DSS Payment Card Industry Data Security Standard"
    ["csa_star"]="CSA STAR Cloud Security Alliance"
    ["itil"]="ITIL Information Technology Infrastructure Library"
    
    # Data Protection
    ["gdpr"]="GDPR General Data Protection Regulation"
    ["dpa2018"]="UK DPA 2018 Data Protection Act"
    ["ccpa_cpra"]="CCPA/CPRA California Consumer Privacy Act"
    ["pipeda"]="PIPEDA Personal Information Protection and Electronic Documents Act"
    ["lgpd"]="LGPD Lei Geral de Proteção de Dados"
    ["popia"]="POPIA Protection of Personal Information Act"
    
    # Testing & Certification Bodies
    ["ecogra"]="eCOGRA eCommerce Online Gaming Regulation and Assurance"
    ["itech_labs"]="iTech Labs Independent Testing Laboratory"
    ["bmm_testlabs"]="BMM Testlabs Gaming Testing Laboratory"
    ["trisigma"]="Trisigma European Testing Laboratory"
    ["gaming_associates"]="Gaming Associates Testing Laboratory"
    
    # Regulatory Jurisdictions
    ["gibraltar"]="Gibraltar Regulatory Authority (GRA)"
    ["alderney"]="Alderney Gambling Control Commission (AGCC)"
    ["isle_of_man"]="Isle of Man Gambling Supervision Commission (GSC)"
    ["curacao"]="Curaçao eGaming"
    ["new_jersey"]="New Jersey Division of Gaming Enforcement (NJDGE)"
    ["pennsylvania"]="Pennsylvania Gaming Control Board (PGCB)"
)

# Create framework order for navigation
framework_keys=(
    "gli" "mga" "ukgc" "g4"
    "soc2" "iso27001" "iso9001" "pci_dss" "csa_star" "itil"
    "gdpr" "dpa2018" "ccpa_cpra" "pipeda" "lgpd" "popia"
    "ecogra" "itech_labs" "bmm_testlabs" "trisigma" "gaming_associates"
    "gibraltar" "alderney" "isle_of_man" "curacao" "new_jersey" "pennsylvania"
)

# Create individual framework reports
for i in "${!framework_keys[@]}"; do
    framework="${framework_keys[$i]}"
    framework_name="${frameworks[$framework]}"
    
    # Determine previous and next framework for navigation
    prev_index=$(( (i - 1 + ${#framework_keys[@]}) % ${#framework_keys[@]} ))
    next_index=$(( (i + 1) % ${#framework_keys[@]} ))
    prev_framework="${framework_keys[$prev_index]}"
    next_framework="${framework_keys[$next_index]}"
    prev_framework_name="${frameworks[$prev_framework]}"
    next_framework_name="${frameworks[$next_framework]}"
    
    cat > "$REPORT_DIR/$framework.md" << EOF
# $framework_name Compliance Report

**Framework**: $framework_name  
**Date**: $(date +"%Y-%m-%d")  
**Time**: $(date +"%H:%M")  
**Auditor**: Auditron AI

## Navigation
- [← Previous: $prev_framework_name](./$prev_framework.md)
- [← Back to Main Report](./index.md)
- [→ Next: $next_framework_name](./$next_framework.md)

## Controls Audited

### [Control ID] - [Control Name]

**Status**: 🔄 **IN PROGRESS**

**Requirements Checked**:
- [ ] Requirement 1
- [ ] Requirement 2
- [ ] Requirement 3

**Evidence Examined**:
- (File paths and evidence will be listed here)

**Findings**:
- (Detailed findings will be documented here)

**Conclusion**: (Compliance determination will be stated here)

## Summary

- **Total Controls**: -
- **Compliant**: -
- **Non-Compliant**: -
- **Observations**: -

## GitHub Issues Created
(Issues will be listed here as they are created)

## Navigation
- [← Previous: $prev_framework_name](./$prev_framework.md)
- [← Back to Main Report](./index.md)
- [→ Next: $next_framework_name](./$next_framework.md)
EOF
done

echo "✅ Created comprehensive compliance report structure in: $REPORT_DIR"
echo ""
echo "Report files created:"
echo "📋 Main Report:"
echo "  - index.md (comprehensive overview)"
echo ""
echo "🎮 iGaming Standards:"
echo "  - gli.md (GLI compliance)"
echo "  - mga.md (MGA compliance)" 
echo "  - ukgc.md (UKGC compliance)"
echo "  - g4.md (G4 compliance)"
echo ""
echo "💻 IT/SaaS Standards:"
echo "  - soc2.md (SOC 2 compliance)"
echo "  - iso27001.md (ISO 27001 compliance)"
echo "  - iso9001.md (ISO 9001 compliance)"
echo "  - pci_dss.md (PCI DSS compliance)"
echo "  - csa_star.md (CSA STAR compliance)"
echo "  - itil.md (ITIL compliance)"
echo ""
echo "🛡️ Data Protection:"
echo "  - gdpr.md (GDPR compliance)"
echo "  - dpa2018.md (UK DPA 2018 compliance)"
echo "  - ccpa_cpra.md (CCPA/CPRA compliance)"
echo "  - pipeda.md (PIPEDA compliance)"
echo "  - lgpd.md (LGPD compliance)"
echo "  - popia.md (POPIA compliance)"
echo ""
echo "🧪 Testing & Certification:"
echo "  - ecogra.md (eCOGRA certification)"
echo "  - itech_labs.md (iTech Labs certification)"
echo "  - bmm_testlabs.md (BMM Testlabs certification)"
echo "  - trisigma.md (Trisigma certification)"
echo "  - gaming_associates.md (Gaming Associates certification)"
echo ""
echo "🏛️ Regulatory Jurisdictions:"
echo "  - gibraltar.md (Gibraltar compliance)"
echo "  - alderney.md (Alderney compliance)"
echo "  - isle_of_man.md (Isle of Man compliance)"
echo "  - curacao.md (Curaçao compliance)"
echo "  - new_jersey.md (New Jersey compliance)"
echo "  - pennsylvania.md (Pennsylvania compliance)"
echo ""
echo "Next steps:"
echo "  1. Run compliance audits for each framework"
echo "  2. Update report files with findings"
echo "  3. Create GitHub issues for non-compliant findings"
echo "  4. Update the main index.md with summary results"